### ISSUE TITLE
Talking about micROScopy

### ISSUE THREAD

**Issue by beniroquai** [acquire-project/acquire-ros#2]
Hi @jeskesen, unfortunately I wasn't able to attend your presentation on this project in person last week in Seatle, but @jacopoabramo told me about your presentation. Great stuff. I had a question a while back about what the micROScope might look like, but I found it really difficult to get started with ROS in general. Would you be up for a quick meeting to discuss a few questions? I couldn't find an email address of yours. If you are interested, you can use the address I linked here: https://github.com/beniroquai. Thanks for pushing this project forward, I'm really excited to see the possibilities in action! :)

**Comment by jeskesen** [comment]
Thanks Benedict!  @jacopoabramo mentioned your interest.  I'll reach out to via email & we'll set up a meeting!

**Comment by beniroquai** [comment]
Perfect! Thanks a lot! :)
