### ISSUE TITLE
Add Launch file for Oryx camera.

### ISSUE THREAD

**Issue by jeskesen** [acquire-project/acquire-ros#8]
This task is to verify that the Oryx Camera works using the [Spinnaker ROS2 driver](https://github.com/ros-drivers/flir_camera_driver/tree/humble-devel) in Linux.   The output will be a launch file so others can reproduce.

A beneficial side effect is that this might start stress testing the concept of passing high-throughput data through the ROS2 middleware.

Driver docs are [here](https://docs.ros.org/en/iron/p/spinnaker_camera_driver/).

**Comment by aliddell** [comment]
Closed by #10
